repos:
  - repo: local
    hooks:
      - id: clang-format
        name: clang-format
        entry: clang-format -i
        language: system
        files: \.(c|cc|cpp|cxx|h|hh|hpp)$
        pass_filenames: true