name: Linux run on x86/GCC/Clang

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-ubuntu24_04_gcc-x64:
    uses: ./.github/workflows/linux_run.yml
    with:
      compiler: gcc
      runner: ubuntu-24.04
    secrets:
      SERVER: ${{ secrets.SERVER }}
      USERNAME: ${{ secrets.USERNAME }}
      PW: ${{ secrets.PW }}
      GHCR_PAT: ${{ secrets.GHCR_PAT }}

  build-ubuntu24_04_clang-x64:
    uses: ./.github/workflows/linux_run.yml
    with:
      compiler: clang
      runner: ubuntu-24.04
    secrets:
      SERVER: ${{ secrets.SERVER }}
      USERNAME: ${{ secrets.USERNAME }}
      PW: ${{ secrets.PW }}
      GHCR_PAT: ${{ secrets.GHCR_PAT }}
